name: java-app
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORKSPACE_PATH: /workspaces/JAVA
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_HOSTNAME: db
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  db-volume:
